apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "WebApi": {
        "Setting1": "{{ .Values.appsettings.webapi.Setting1 }}",
        "Setting2": "{{ .Values.appsettings.webapi.Setting2 }}"
      },
      "CronJob": {
        "Schedule": "{{ .Values.appsettings.cronjob.schedule }}",
        "SettingA": "{{ .Values.appsettings.cronjob.SettingA }}"
      }
    }