{{- if .Values.certificates.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "myapp.fullname" . }}-cert
spec:
  secretName: {{ include "myapp.fullname" . }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.certificates.commonName }}
  dnsNames:
    - {{ .Values.certificates.commonName }}
{{- end }}