apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-webapi-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mywebapi.name" . }}
  ports:
    - port: 80
      targetPort: 80